### ISSUE TITLE
Invalid signature using `commons-lang3:3.11`

### ISSUE THREAD

**Issue by hypr2771** [iyzico/iyzipay-java#105]
## Context

We are using:

- JDK 14
- `com.iyzipay:iyzipay-java:2.0.69`

## Case

We updated our `org.apache.commons:commons-lang3` from `3.10` to `3.11` and now are facing:

```properties
status=failure
errorCode=1000
errorMessage=Invalid signature
```

**Comment by gncj** [comment]
We had the same problem, and needed to return to 3.10 version of org.apache.commons:commons-lang3

**Comment by hypr2771** [comment]
@gncj I'll try to fill a PR but I don't know the politics of this repository regarding backwards compatibility.
@beremaran mind giving us guidelines please?
