### ISSUE TITLE
Readme points to dependency that does not work

### ISSUE THREAD

**Issue by GlennVanSchil** [iyzico/iyzipay-java#123]
In the README of the current release version (v2.0.113) there is a reference to an incorrect maven dependency

```xml
<dependency>
  <groupId>com.iyzipay</groupId>
  <artifactId>iyzipay-java</artifactId>
  <version>2.0.113</version>
</dependency>
```
The latest version on mvnrepository is still v2.0.84. Same for the maven central reference in the README of the current release version.

**Comment by erdemdmr** [comment]
Thanks @GlennVanSchil
