### ISSUE TITLE
Upgrade subscription ilgili datayı içermiyor

### ISSUE THREAD

**Issue by efekancakmak** [iyzico/iyzipay-java#146]
English Below,

Selamlar,

Iyzicoya python üzerinden abonelik yükseltmesi istek attığımızda aşağıdaki formatta cevap alıyoruz.

`
{
    "status": "success",
    "systemTime": 1678446184680,
    "data": {
        "referenceCode": "abcd",
        "parentReferenceCode": "abcd",
        "pricingPlanReferenceCode": "abcd",
        "customerReferenceCode": "abcd",
        "subscriptionStatus": "ACTIVE",
        "trialDays": 0,
        "createdDate": 1678446184629,
        "startDate": 1678446184623
    }
}`

bu dataya iyzipay-java'daki SubscriptionOperation.upgrade metodundan gelen cevap ile erişemiyoruz. data fieldına erişim mi istenmiyor? source kodunuzu incelediğimde dataya erişmek için bir method eklememişsiniz ama o zaman fieldda neden var?
Aynı durum SubscriptionSearch'te de geçerli. Kullanıdığım sürüm 2.0.115.

İyi çalışmalar dilerim.

-------------------------------------------------

Hi,

We achieve the response below when sending request to Iyzico via python for subscription upgrade.

`{ "status": "success", "systemTime": 1678446184680, "data": { "referenceCode": "abcd", "parentReferenceCode": "abcd", "pricingPlanReferenceCode": "abcd", "customerReferenceCode": "abcd", "subscriptionStatus": "ACTIVE", "trialDays": 0, "createdDate": 1678446184629, "startDate": 1678446184623 } }`

However, we can not access this data from response of SubscriptionOperation.upgrade method. Is data field hidden? If yes, why does data field exist? This problem also occurs when using SubscriptionSearch. Used version is 2.0.115.

Good day.

**Comment by efekancakmak** [comment]
Hi,

We achieve the response below when sending request to Iyzico via python for subscription upgrade.

 { "status": "success", "systemTime": 1678446184680, "data": { "referenceCode": "abcd", "parentReferenceCode": "abcd", "pricingPlanReferenceCode": "abcd", "customerReferenceCode": "abcd", "subscriptionStatus": "ACTIVE", "trialDays": 0, "createdDate": 1678446184629, "startDate": 1678446184623 } }

However, we can not access this data from response of SubscriptionOperation.upgrade method. Is data field hidden? If yes, why does data field exist? This problem also occurs when using SubscriptionSearch. Used version is 2.0.115.

Good day.

**Comment by byasarcse** [comment]
Merhabalar, 

https://github.com/iyzico/iyzipay-java/releases/tag/v2.0.120 versiyonumuz içerisinde gerekli yapı eklenmiştir.

**Comment by byasarcse** [comment]
Merhabalar,

https://github.com/iyzico/iyzipay-java/releases/tag/v2.0.120 versiyonumuz içerisinde gerekli yapı eklenmiştir.
