### ISSUE TITLE
BasicPayment.create command triggers an error in Android Java.

### ISSUE THREAD

**Issue by MoonWatcha** [iyzico/iyzipay-java#27]
Exact error is: Caused by: java.lang.NoSuchMethodError: No static method encodeBase64String([B)Ljava/lang/String; in class Lorg/apache/commons/codec/binary/Base64; or its super classes (declaration of 'org.apache.commons.codec.binary.Base64' appears in /system/framework/org.apache.http.legacy.boot.jar)

I guess it's necessary to use android.util.Base64 library instead of Apache Base64. Do you have a working version of java codes provided for Android exactly? Or am I doing something wrong?

**Comment by yyenigun** [comment]
Actually we don't have an Android client. Our clients usually implement a web service and call them from mobile devices. You can also implement an Android client using this Java client and contribute to iyzico Github repository.
