### ISSUE TITLE
Functional test assertions must be updated after mock response authcode regulation

### ISSUE THREAD

**Issue by kadriyedogan** [iyzico/iyzipay-java#56]

**Comment by sotuzun** [comment]
@kadriyedogan this must be fixed in your previous commits. Could you please check and close the issue?

**Comment by kadriyedogan** [comment]
@sotuzun This issue fixed with https://github.com/iyzico/iyzipay-java/commit/30c74613bacdb3abdcc593597d5ec98945e02d64 commit.
